image: docker.io/ruby:3.1

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

setvars:
  stage: .pre
  script:
    - |
      if [[ -n $CI_COMMIT_TAG ]]; then
        echo "VERSION=$CI_COMMIT_TAG" >> version.env
      else
        echo "VERSION=$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" >> version.env
      fi
      source version.env
      echo "TARBAL_FILENAME=blog-$VERSION.tar.bz2" >> version.env
    - cat version.env
  artifacts:
    reports:
      dotenv: version.env

build:
  stage: build
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d blog
    - tar cjvf "$TARBAL_FILENAME" ./blog
    - echo "DOWNLOAD_LINK=$CI_JOB_URL/artifacts/raw/$TARBAL_FILENAME?inline=false" >> download.env
    - cat download.env
  artifacts:
    paths:
      - "*.bz2"
    reports:
      dotenv: download.env
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created for version $VERSION.'
    assets:
      links:
        - name: '$TARBAL_FILENAME'
          url: '$DOWNLOAD_LINK'
